name: perm-sync
channels:
  - conda-forge
  - pytorch    
  - nvidia     
dependencies:
  - python =3.11
  - numpy       
  - scipy       
  - pytorch =2.2
  - pytorch-cuda =12.1    
  - tqdm              
  - wandb             
  - matplotlib        
  - pip
  - pip:              
      - networkx
      - torch-geometric==2.5.1      
